/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BricsRouteImport } from './routes/brics'
import { Route as FacilityFacilityIdRouteImport } from './routes/facility.$facilityId'
import { Route as ResourceResourceRouteImport } from './routes/resource.$resource'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BricsRoute = BricsRouteImport.update({
  id: '/brics',
  path: '/brics',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityFacilityIdRoute = FacilityFacilityIdRouteImport.update({
  id: '/facility/$facilityId',
  path: '/facility/$facilityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceResourceRoute = ResourceResourceRouteImport.update({
  id: '/resource/$resource',
  path: '/resource/$resource',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brics': typeof BricsRoute
  '/facility/$facilityId': typeof FacilityFacilityIdRoute
  '/resource/$resource': typeof ResourceResourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brics': typeof BricsRoute
  '/facility/$facilityId': typeof FacilityFacilityIdRoute
  '/resource/$resource': typeof ResourceResourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brics': typeof BricsRoute
  '/facility/$facilityId': typeof FacilityFacilityIdRoute
  '/resource/$resource': typeof ResourceResourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brics' | '/facility/$facilityId' | '/resource/$resource'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brics' | '/facility/$facilityId' | '/resource/$resource'
  id:
    | '__root__'
    | '/'
    | '/brics'
    | '/facility/$facilityId'
    | '/resource/$resource'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BricsRoute: typeof BricsRoute
  FacilityFacilityIdRoute: typeof FacilityFacilityIdRoute
  ResourceResourceRoute: typeof ResourceResourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brics': {
      id: '/brics'
      path: '/brics'
      fullPath: '/brics'
      preLoaderRoute: typeof BricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/$facilityId': {
      id: '/facility/$facilityId'
      path: '/facility/$facilityId'
      fullPath: '/facility/$facilityId'
      preLoaderRoute: typeof FacilityFacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$resource': {
      id: '/resource/$resource'
      path: '/resource/$resource'
      fullPath: '/resource/$resource'
      preLoaderRoute: typeof ResourceResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BricsRoute: BricsRoute,
  FacilityFacilityIdRoute: FacilityFacilityIdRoute,
  ResourceResourceRoute: ResourceResourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
